apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deployment
  namespace: my-namespace
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: my-tomcat
  template:
    metadata:
      labels:
        app: my-tomcat
    spec:
      containers:
        - name: my-tomcat-container
          image: gcr.io/kodekloud/centos.ssh-enabled:tomcat
          ports:
            - containerPort: 8080    
