apiVersion: v1
kind: service
metadata:
  name: tomcat-service
  namespace: my-namespace
spec:
  type: NodePort
  selector:
    app: my-tomcat
  ports:
    - port: 80
      targetport: 8080
      nodePort: 3227
